#!/bin/bash
######################################################
# Starting script
# Author: Stoku
# Copyright 2022
######################################################

#start [dir] [options] //[username]

function Start() {
    user="$1"
    server="$2"
    options="$3"

    echo "Trying to start server \"${server}\" as \"${user}\"."
    path="/home/${user}/${server}"
    
    if [ -z ${options} ]; then
        echo "Default startup parameters (Autostarter and DEcho enabled)."
    elif [ ${options} = "-a" ]; then
        echo "Autorestarter enabled."
    elif [ ${options} = "-d" ]; then
        echo "DEcho enabled."
    elif [ ${options} = "-ad" ]; then
        echo "Autostarter and DEcho enabled."
    elif [ ${options} = "-off" ]; then
        echo "Autostarter and DEcho disabled."
        cd "${path}" && screen -AmdS "${server}" ./${path}/Server.bin
        return 1
    fi

	if [ -d $path ]; then
        if ! screen -ls | grep -w -q "${server}"; then
            echo "Found path \"${path}\", starting."
		    /bin/bash /bin/watcher --start "${path}" "${server}" "${options}"
            return 1
        else
            echo "\"${server}\" is already running."
        fi
	else
		echo "Path \"${path}\" not found."
        return 0
	fi
}

function print_help(){
    echo "Start script usage:"
	echo "start [dir] [options]"
    echo ""
    echo "Options:"
    echo "-a    - enable Autorestarter"
    echo "-d    - enable DEcho"
    echo "-ad   - enable Autorestarter and DEcho"
    echo "-off  - disable Autorestarter and DEcho"
    echo "Default: -re"
}

if [ -z $1 ]; then
	print_help
else
	Start $USER $1 $2
fi

#ls -d */ list dir
