#!/bin/bash

function print_help(){
    echo "Stop script usage:"
	echo "stop [dir]"
}

function Stop(){
    if screen -list | grep -w -q "${1}"; then
        echo "Terminating ${1}"
        screen -X -S "$1"_watcher quit
        screen -X -S $1 quit
    else
        echo "${1} not found."
    fi

    screen -ls
}

if [ -z $1 ]; then
	print_help
else
	Stop $1
fi
