#!/bin/bash
######################################################
# Watcher script
# Author: Stoku, XenoN
# Copyright 2022
######################################################

this_script_name=${0##*/}
timer=3
server_path="$2"
server_name="$3"
mode="$4"
run_echo_script=".echo_buffer.sh"

echo "Current watcher state: ${1}"
echo "Server path: ${2}"
echo "Server name: ${3}"
echo "Mode: ${4}"

if [ -z "$4" ]; then
    echo "No mode specified. Setting default mode -ad"
    mode="-ad"
else
    #echo "watcher: setting mode ${4}"
    mode="$4"
fi

if [ "$1" = "--start" ]; then
    > "${server_path}/${run_echo_script}"  #cleanup

    # Start watcher
    if ! screen -ls | grep -w -q "${server_name}_watcher"; then
        echo "Starting \"${server_name}_watcher\" process."
    	screen -AmdS "${server_name}_watcher" watch -n $timer /bin/bash "/bin/watcher" --loop "$server_path" "$server_name" "$mode"
    fi
    # Start server
    if ! screen -ls | grep -w -q "${server_name}"; then
        echo "Starting \"${server_name}\" process."
        cd "${server_path}" && screen -AmdS ${server_name} "${server_path}/Server.bin"
    fi

    echo ""
    screen -ls

elif [ "$1" = "--stop" ]; then
	screen -X -S "${server_name}_watcher" quit
	screen -X -S "${server_name}" quit
	screen -ls

elif [ "$1" = "--loop" ]; then
    if [ "$mode" = "-d" ] || [ "$mode" = "-ad" ]; then
        echo "${server_path}"
	cd "${server_path}" && ${server_path}/.echo_buffer.sh
        > "${server_path}/${run_echo_script}"
    fi

    if [ "$mode" = "-a" ] || [ "$mode" = "-ad" ]; then
        if ! screen -ls | grep -w -q "${server_name}"; then
            echo "Autorestarter: process \"${server_path}/Server.bin\" not found. Restarting."
    	    cd "${server_path}" && screen -AmdS ${server_name} "${server_path}/Server.bin"
        fi
    fi
else
	echo "Usage:"
	echo "[--start] - uruchamia pętlę co ${timer} sekund/y w screen pod nazwą ${server}_discord_watch"
	echo "[--stop]  - ubija pętlę"
	echo "[--loop]  - do użytku przez skrypt | Parametr testowy; uruchamia plik ${run_script}"
	echo "            i czyści jego zawartość"
fi
